server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/invmanage?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: happycode
    password: 31Caxtcttp2woNnr
    hikari:
      maximum-pool-size: 20          # 最大连接数
      minimum-idle: 2                # 最小空闲连接数
      idle-timeout: 30000            # 空闲连接超时时间（毫秒）
      max-lifetime: 1800000          # 最大存活时间（毫秒）
      connection-timeout: 30000      # 获取连接超时时间（毫秒）
      validation-timeout: 5000       # 验证连接的超时时间（毫秒）
      connection-test-query: SELECT 1 # 验证连接是否有效的 SQL
  jpa:
    hibernate:
      ddl-auto: update  # 设定 JPA 自动处理数据库表结构
    show-sql: true  # 打印 SQL 语句
    properties:
      hibernate:
        format_sql: true  # 格式化 SQL
        generate_statistics: false
  jackson:
    serialization:
      indent-output: true  # JSON 美化输出
logging:
  file:
    name: ${LOG_DIR:D:/logs}/application.log  # 默认日志路径为 D:/logs/application.log
